### PR TITLE
Revamp OSList system

### PR DESCRIPTION
**Pull request by webdev03**
Not tested yet on Chrome - can you tell me the results?

### CODE REVIEW

**Comment by hello-smile6** [comment]
Okay, conflicts?

**Comment by hello-smile6** [comment]
@webdev03 Run `git pull`, I made a commit

**Comment by hello-smile6** [comment]
You can revert that commit now

**Comment by hello-smile6** [comment]
Figured out the icon issue. The icons can't be indented. Going to fix.

**Comment by hello-smile6** [comment]
Fixed an icon.
# Before

# After

**Comment by hello-smile6** [comment]
Merging, anything else?

**Comment by webdev03** [comment]
Wait

**Comment by webdev03** [comment]
Lines 117 and 118 both use deprecated `navigator.platform` is there an alternative?

**Comment by hello-smile6** [comment]
Let me see

**Comment by webdev03** [comment]
Also, can I have some ASCII art to put for "Unknown"?

**Comment by hello-smile6** [comment]
Yes, we could use `navigator.userAgentData.platform`, but it'd require a major rewrite and every platform check would need changed. Also, we use the platform as the sole source of truth for both Windows and Linux. We could make it use the new version and fallback when necessary, but it'd take a lot of work. It'd be worth it, but it's definitely not a 2-minute change.

**Comment by hello-smile6** [comment]
> Also, can I have some ASCII art to put for "Unknown"?

Sure. Do a question mark.

**Comment by hello-smile6** [comment]
Could you do a new PR for a question mark after this is merged, by chance? This one's a bit big.

**Comment by hello-smile6** [comment]
You didn't tell prettier to ignore the Windows icon

**Comment by hello-smile6** [comment]
I got it

**Comment by hello-smile6** [comment]
I fixed it

**Comment by webdev03** [comment]
> Wait, some of the browser-specific code is missing question marks!

?

**Comment by webdev03** [comment]
They don't need question marks - it's a standard right?

**Comment by hello-smile6** [comment]
> They don't need question marks - `navigator.userAgent` it's a standard right?

Not for Node. I'm trying to make it work in Node. If it will work, I can write tests easier.

**Comment by webdev03** [comment]
I'll make it work for Node soon if you want. We can use TSUP to export to UMD/AMD/CJS/ESM

**Comment by hello-smile6** [comment]
Could you revert https://github.com/hello-smile6/neofetch-js/pull/9/commits/8c5847986a6f8de7090498124b703b842cb84015 ? I like the new defaults!

**Comment by hello-smile6** [comment]
The old defaults will make Node support easier.

**Comment by hello-smile6** [comment]
@webdev03 Fixed the defaults

**Comment by webdev03** [comment]
Oh it's because Unknown hasn't been added to osList yet. If you can provide me the ASCII for Unknown then I can use it!

**Comment by hello-smile6** [comment]
> Oh it's because Unknown hasn't been added to osList yet. If you can provide me the ASCII for Unknown then I can use it!

Just use this for now. :)
```
?
```
Maybe I'll push an update later with a better question mark.

**Comment by hello-smile6** [comment]
Just set formatOnPaste to false using vscode settings. That should help for those who have vscode configured to automatically format code.

**Comment by hello-smile6** [comment]
Okay!

**Pull request merged**
