### PR TITLE
add ios detection

### PR DESCRIPTION
**Pull request by webdev03**
Not tested!

### CODE REVIEW

**Comment by hello-smile6** [comment]
Doesn't seem to work, can you test with xcode or something?

**Comment by webdev03** [comment]
OK

**Comment by webdev03** [comment]
I tested on my iPhone it works even without da8190b

**Comment by hello-smile6** [comment]
> I tested on my iPhone it works even without [da8190b](https://github.com/hello-smile6/neofetch-js/commit/da8190bd5a2e0740c8a56dbb3315c6479bcdce91)

Okay. If you detect the string "iPad", it should detect iPads. It looked like it didn't have it yet.

**Comment by hello-smile6** [comment]
Was just using device emulation in devtools to test, btw

**Comment by hello-smile6** [comment]
Looks good, maybe we should alias `Neofetch.osList.apple` to `Neofetch.osList.macos`...

**Comment by webdev03** [comment]
I'm going to revamp the osList system after this gets merged.

**Comment by hello-smile6** [comment]
> I'm going to revamp the osList system after this gets merged.

Sounds good

**Comment by hello-smile6** [comment]
> ??

Looking at the analytics data, counter.dev shows .local and local IP addresses for some reason. I'm going to open an issue.

**Comment by hello-smile6** [comment]
@webdev03 https://github.com/ihucos/counter.dev/issues/59

**Comment by hello-smile6** [comment]
> ??

Just wanted you to know that it showed that, because it'd be wrong to not tell you.

**Comment by hello-smile6** [comment]
@webdev03 https://github.com/hello-smile6/neofetch-js/commit/942b7ed437a0047ad00d7b5dd8416a868cc29aee

**Pull request merged**
