### PR TITLE
web-ify

### PR DESCRIPTION
**Pull request by webdev03**
Not tested yet..

### CODE REVIEW

**Comment by webdev03** [comment]
This shouldn't pollute the global namespace..

**Comment by webdev03** [comment]
You could also use ES6 modules instead.

**Comment by hello-smile6** [comment]
1. Modules aren't an option with local development.
2. It seems like you have some variables to update. Just use find/replace in vscode to fix those.

Otherwise, looks good.

**Comment by webdev03** [comment]
I think that let is scoped to the function only? I'm working on an example in this PR.

**Comment by hello-smile6** [comment]
> I think that let is scoped to the function only? I'm working on an example in this PR.

I have an example already, going to deploy to vercel and test it.

**Comment by hello-smile6** [comment]
@webdev03 Adding vercel, could you make a PR with what's needed to make vercel be quiet?

**Review by hello-smile6 — CHANGES_REQUESTED** [review]
Could you fix the `oses` instances? Also, I need to make a change before this is merged which will affect the same lines, so if you waited until I fix it before correcting them, I'd appreciate it.
Why is neofetch capitalized? It's not a class. And shouldn't you export the Neofetch object instead of making it a property of `module.exports`?

**Comment by hello-smile6** [comment]
> Example doesn't work - You don't need to use XTerm just simple CSS will do!

I always use xtermjs for anything that outputs data like that. Also, if this is used with Node, it needs support for different line endings.

**Comment by hello-smile6** [comment]
Made the change I needed to do

**Comment by webdev03** [comment]
It's window.Neofetch and it is capital to prevent some confusion with other variables

**Comment by hello-smile6** [comment]
Checking page performance, just to make sure there isn't a crazy CPU load increase

**Review by hello-smile6 — APPROVED** [review]
Looks good, waiting in case you need to change things

**Comment by hello-smile6** [comment]
> My fork, my wish 😄

Oh. I never delete branches, and actively undelete them sometimes on github orgs.

**Pull request merged**
